********************************************************************
/* BUILDING WORKER-LEVEL PANEL
- Author: Bernardo Dias de Aquino Nascimento (current Research Assistant)
- Last updated: 19/11/2025

Disclaimer:
Every user with access to the RAIS data may access this file. This file may NOT leave the server. This file loops around selected years in order to build a monthly worker panel. Some filters and variables are made available. Monthly tenure variable may be improved by using hire_date and sep_date variables. If you have suggestions on how to improve this code, please contact the current RA. Comments are always welcome!
- Current RA: Bernardo Dias de Aquino Nascimento (bernardo.nascimento@aluno.puc-rio.br)

Instructions:
1) Do NOT edit this file. Copy and paste this code in your personal folder inside the server. You may edit the code inside your folder as needed. For instance, if you wish to build a quarterly panel instead of monthly, the code may easily be adapted to that
2) Change the global variables FIRST_YEAR and LAST_YEAR to the years you want to build the panel
3) Change the global variable REGIONS for the regions you want to build the panel
4) Check for variables of interest
5) Run the code
*/
********************************************************************

**************************
******* Sections *********
**************************
* I. Calculating monthly contracts
* II. Formatting
**************************

clear all
cap log close
set more off
set seed 12345

set rmsg on

global FIRST_YEAR 2015
global LAST_YEAR  2019
global SECOND_YEAR = ${FIRST_YEAR} + 1
global REGIONS = "centrooeste norte nordeste sul sp mgrjes"

local FIRST_YEAR  ${FIRST_YEAR}
local SECOND_YEAR ${SECOND_YEAR}
local LAST_YEAR   ${LAST_YEAR}
local REGIONS     ${REGIONS}



********************************
* I. Calculating monthly contracts
********************************

foreach year of numlist `FIRST_YEAR'(1)`LAST_YEAR'{
foreach month of numlist 1(1)12 {
foreach region of `REGIONS' {
display "*********************************************"
display `year'
display `month'
display `region'
display "*********************************************"
	
*Opening the datasets
use "U:\Desktop\RA_RAIS\RAIS\data\contract_level\\`year'\\`year'`region'.dta", clear

* Droping irregular ids
drop if enc_id_worker == "00000000000"

* Droping duplicates
duplicates drop

* Generating variables
gen year = `year'
gen month = `month'

* Keeping only certain contracts (in this case, open-ended CLT contracts)
keep if inlist(contr_type, 10, 15, 20, 25)

* Keeping only workers with positive earnings
keep if avg_w_real > 0

* Keeping only certain firms (in this case, private sector firms)
keep if inlist(legal_nature, 2046, 2054, 2062, 2070, 2076, 2089, 2097, 2100, 2119) | inlist(legal_nature, 2127, 2135, 2143, 2151, 2160, 2178, 2194, 2208, 2216) | inlist(legal_nature, 2224, 2232, 2240, 2259, 2267, 2275, 2283, 2291, 2292) | inlist(legal_nature, 2305, 2313, 2321, 2330)

* Droping people hired before a certain year (in this case, 1991)
drop if hire_year < 1991 | hire_year == . 

* Keeping prime-age workers
keep if age >= 18 & age <= 64
	
* Keeping full-time jobs
keep if hours >= 30

* Droping if gender is wrong
bysort enc_id_worker: egen msex=mean(gender)
drop if msex>0 & msex<1
drop msex
		
* Transforming the format of some variables to facilitate the collapse
destring enc_id_firm cbo1994 sector, replace dpcomma force
format enc_id_firm %16.0g
format cbo1994 %16.0g
format sector %16.0g

* Keeping individuals that:
* (1) Were hired before or during the month and were separated during or after the month;
* (2) Were hired before or during the month and were not separated during the year; 
* (3) Were hired before the year and separated during or after the month;
* (4) Were hired before the year and were not separated during the year.
keep if (hire_month<=`month' & hire_year==`year' & sep_month>=`month' | hire_month<=`month' & hire_year==`year' & empl_31dec==1 | hire_year<`year' & sep_month>=`month' | hire_year<`year' & empl_31dec==1)

* Calculating monthly tenure --> can be improved
	gen tenure_mon = .
	* 1) Hired before the year and not separated the year or separated after the month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = 1 if (hire_year < `year' & (sep_month==0 | sep_month>`month'))
	* 2) Hired before the year and separated in the reference month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = sep_month - (`month') if (hire_year < `year' & sep_month==`month' & empl_31dec==0)
	* 3) Hired in the month and not separated in the year
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = tenure - (12 - `month') if (hire_year==`year' & hire_month==`month' & empl_31dec==1)
	* 4) Hired before the month and not separated in the year
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = 1 if (hire_year==`year' & hire_month<`month' & empl_31dec==1)
	* 5) Hired in the month and separated after the month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = tenure - (sep_month - `month') if (hire_year==`year' & hire_month==`month' & sep_month>`month' & empl_31dec==0)
	* 6) Hired before the month and separated after the month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = 1 if (hire_year==`year' & hire_month<`month' & sep_month>`month' & empl_31dec==0)
	* 7) Hired before the month and separated in the month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = `month' - sep_month + 1 if (hire_year==`year' & hire_month<`month' & sep_month==`month' & empl_31dec==0)
	* 8) Hired and separated in the month
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = tenure if (hire_year==`year' & hire_month==`month' & sep_month==`month' & empl_31dec==0)
	* If tenure_mon is negative, it means the worker was hired at the end of the previous month. Therefore, tenure is some decimal <1
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = tenure_mon + 1 if tenure_mon < 0
	di "**************************************************************"
	di "Check here if there are any negatives"
	di "**************************************************************"
	bysort enc_id_worker enc_cnpj_cei hire_year: replace tenure_mon = 0 if tenure_mon < 0


* Selecting wage for the respective month
gen real_wage = ..
replace real_wage = w_jan_real if `month' == 1
replace real_wage = w_feb_real if `month' == 2
replace real_wage = w_mar_real if `month' == 3
replace real_wage = w_apr_real if `month' == 4
replace real_wage = w_may_real if `month' == 5
replace real_wage = w_jun_real if `month' == 6
replace real_wage = w_jul_real if `month' == 7
replace real_wage = w_aug_real if `month' == 8
replace real_wage = w_sep_real if `month' == 9
replace real_wage = w_oct_real if `month' == 10
replace real_wage = w_nov_real if `month' == 11
replace real_wage = w_dec_real if `month' == 12

gen nom_wage = 
replace nom_wage = w_jan_nom if `month' == 1
replace nom_wage = w_feb_nom if `month' == 2
replace nom_wage = w_mar_nom if `month' == 3
replace nom_wage = w_apr_nom if `month' == 4
replace nom_wage = w_may_nom if `month' == 5
replace nom_wage = w_jun_nom if `month' == 6
replace nom_wage = w_jul_nom if `month' == 7
replace nom_wage = w_aug_nom if `month' == 8
replace nom_wage = w_sep_nom if `month' == 9
replace nom_wage = w_oct_nom if `month' == 10
replace nom_wage = w_nov_nom if `month' == 11
replace nom_wage = w_dec_nom if `month' == 12

drop w_* 

* Filtering for workers with multiple jobs
by enc_id_worker year: gen n_jobs = _N
by enc_id_worker year: replace n_jobs = 1 if reas_sep != 0 
by enc_id_worker year: replace n_jobs = 1 if hire_type != 0 & reas_sep[_n-1] != 0 & reas_sep[_n-2] != 0 & reas_sep[_n-3] != 0
	
	* Droping workers with more than 3 jobs in the same month
	drop if n_jobs > 3
		
	* Keeping the job with the largest tenure
	by enc_id_worker year: egen max_tenure = min(hire_year)
	drop if hire_year != max_tenure & n_jobs > 1
		
	* Keeping the job with the biggest wage
	by enc_id_worker year: egen max_wage = max(real_wage)
	drop if real_avg_w != max_wage & n_jobs > 1

	* Droping unecessary variables	
	drop max_wage max_tenure

* Sorting
sort enc_id_worker

*Salving and appending
if year==`FIRST_YEAR' & month==1 & region=="centrooeste" {
	save "INSERT THE PATH OF THE FILE YOU WANT TO SAVE", replace
} 
else {
	save "INSERT THE PATH OF THE AUXILIARY FILE YOU WANT TO SAVE", replace
	use "INSERT THE PATH OF THE FILE YOU WANT TO SAVE", clear
	append using "INSERT THE PATH OF THE AUXILIARY FILE YOU WANT TO SAVE"
	save "INSERT THE PATH OF THE FILE YOU WANT TO SAVE", replace
	erase "INSERT THE PATH OF THE AUXILIARY FILE YOU WANT TO SAVE"
}


}
}
}



******************************************
* II. Formatting
******************************************

* Calling and ordering the data
use "INSERT THE PATH OF THE FILE YOU WANT TO SAVE", clear
sort enc_id_worker year month

* Creating time series ids
destring enc_id_worker, generate(enc_id_worker_num) force
format enc_id_worker_num %11.0g
gen ym = ym(year, month)
format ym %tm
xtset enc_id_worker_num ym

* Forcing a balanced panel
tsfill, full
replace year = year(dofq(ym))
replace month = month(dofm(ym))

* Filling in the values for some variables
foreach v of varlist worker_munic state gender race birth_date schooling nationality arrival_year ind_disabled type_disability enc_cpf_worker enc_ctps_worker {
	by cnpj_num: replace `v' = `v'[_n-1] if missing(`v')
}
gsort enc_id_worker_num -ym
foreach v of varlist worker_munic state gender race birth_date schooling nationality arrival_year ind_disabled type_disability enc_cpf_worker enc_ctps_worker  {
	by cnpj_num: replace `v' = `v'[_n-1] if missing(`v')
}
sort enc_id_worker_num ym

* Creating the worker's first appearance variable
by enc_id_worker_num: gen first_obs = [age != .]
gen enter = [age != . & year != `FIRST_YEAR' & month != 1]

* Creating the worker's last appearance variable
gsort enc_id_worker_num -ym
by cnpj_num: gen last_nonzero = [age != .]
gen close = [age != . & last_nonzero == 1 & year != `LAST_YEAR' & month != 12]
sort enc_id_worker_num ym

* Deleting the firms that only appear in some years, without closing or opening
by enc_id_worker_num: egen drop_flag = max(first_obs == 1 & enter == 0 & year != `FIRST_YEAR' & month != 1)
drop if drop_flag == 1
drop drop_flag
by enc_id_worker_num: egen drop_flag = max(last_nonzero == 1 & close == 0 & year != `LAST_YEAR' & month != 12)
drop if drop_flag == 1
drop drop_flag

* Deleting the observations before the first and after the last appearance of the worker
by enc_id_worker_num: gen saiu = 1 if close[_n-1] == 1
by enc_id_worker_num: replace saiu = 1 if saiu[_n-1] == 1
drop if saiu == 1
gsort enc_id_worker_num -ym
by enc_id_worker_num: gen entrou = 1 if enter[_n-1] == 1
by enc_id_worker_num: replace entrou = 1 if entrou[_n-1] == 1
drop if entrou == 1
sort enc_id_worker_num ym

* Dropping unecessary variables
drop first_obs last_nonzero saiu entrou

* Creating recall variable
capture qui drop recall
gen recall = . 
bysort enc_id_worker enc_cnpj_cei: replace recall = 1 if (hire_year > hire_year[_n-1] | hire_year == hire_year[_n-1] & hire_month > hire_month[_n-1]) & _n > 1 & reas_sep[_n-1] != 0
replace recall = 0 if recall == . & _n > 1

* Summing up tenure
bysort enc_id_worker enc_cnpj_cei hire_year: gen sum_tenure = sum(tenure_mon)
drop tenure
rename sum_tenure tenure

*Saving final dataset
xtset enc_id_worker ym
save "INSERT THE PATH OF THE FILE YOU WANT TO SAVE", replace
